/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.InstrumentoCordasVO;
import servicos.InstrumentoCordaServicos;


/**
 *
 * @author William Soares
 * @since 05/07/2018
 * @version 1.0
 */
public class GUICadInstrumentosCordas extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadInstrumentosCordas
     */
    public GUICadInstrumentosCordas() {
        initComponents();
        jlMarcaCordaErro.setVisible(false);
        jlModeloCordaErro.setVisible(false);
        jlAnoCordaErro.setVisible(false);
        jlValorCustoCordaErro.setVisible(false);
        jlQuantidadeCordaErro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlMarcaCorda = new javax.swing.JLabel();
        jlModeloCorda = new javax.swing.JLabel();
        jtMarcaCorda = new javax.swing.JTextField();
        jtModeloCorda = new javax.swing.JTextField();
        jlValorCorda = new javax.swing.JLabel();
        jtValorCustoCorda = new javax.swing.JTextField();
        jlQuantidadeCorda = new javax.swing.JLabel();
        jtQuantidadeCorda = new javax.swing.JTextField();
        jlAnoCorda = new javax.swing.JLabel();
        jtAnoCorda = new javax.swing.JTextField();
        jlMarcaCordaErro = new javax.swing.JLabel();
        jlModeloCordaErro = new javax.swing.JLabel();
        jlAnoCordaErro = new javax.swing.JLabel();
        jlValorCustoCordaErro = new javax.swing.JLabel();
        jlQuantidadeCordaErro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbCadastrarCorda = new javax.swing.JButton();
        jbLimparCorda = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Instrumento (Corda)");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlMarcaCorda.setText("Marca");

        jlModeloCorda.setText("Modelo");

        jtMarcaCorda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMarcaCordaFocusLost(evt);
            }
        });
        jtMarcaCorda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtMarcaCordaKeyPressed(evt);
            }
        });

        jtModeloCorda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtModeloCordaFocusLost(evt);
            }
        });
        jtModeloCorda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtModeloCordaKeyPressed(evt);
            }
        });

        jlValorCorda.setText("Valor Custo");

        jtValorCustoCorda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorCustoCordaFocusLost(evt);
            }
        });
        jtValorCustoCorda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValorCustoCordaKeyPressed(evt);
            }
        });

        jlQuantidadeCorda.setText("Quantidade");

        jtQuantidadeCorda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuantidadeCordaFocusLost(evt);
            }
        });
        jtQuantidadeCorda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtQuantidadeCordaKeyPressed(evt);
            }
        });

        jlAnoCorda.setText("Ano");

        jtAnoCorda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAnoCordaFocusLost(evt);
            }
        });
        jtAnoCorda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAnoCordaKeyPressed(evt);
            }
        });

        jlMarcaCordaErro.setForeground(java.awt.Color.red);
        jlMarcaCordaErro.setText("*Preencha este campo");

        jlModeloCordaErro.setForeground(java.awt.Color.red);
        jlModeloCordaErro.setText("*Preencha este campo");

        jlAnoCordaErro.setForeground(java.awt.Color.red);
        jlAnoCordaErro.setText("*Preencha este campo");

        jlValorCustoCordaErro.setForeground(java.awt.Color.red);
        jlValorCustoCordaErro.setText("*Preencha este campo");

        jlQuantidadeCordaErro.setForeground(java.awt.Color.red);
        jlQuantidadeCordaErro.setText("*Preencha este campo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlMarcaCorda)
                                .addGap(31, 31, 31)
                                .addComponent(jtMarcaCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlModeloCorda)
                                    .addComponent(jlAnoCorda))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtModeloCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtAnoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlValorCorda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtValorCustoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlQuantidadeCorda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtQuantidadeCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlMarcaCordaErro, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jlModeloCordaErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlAnoCordaErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlValorCustoCordaErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlQuantidadeCordaErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMarcaCorda)
                    .addComponent(jtMarcaCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMarcaCordaErro))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlModeloCorda)
                    .addComponent(jtModeloCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlModeloCordaErro))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAnoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAnoCorda)
                    .addComponent(jlAnoCordaErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorCorda)
                    .addComponent(jtValorCustoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValorCustoCordaErro))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQuantidadeCorda)
                    .addComponent(jtQuantidadeCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidadeCordaErro))
                .addGap(36, 36, 36))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrarCorda.setText("Cadastrar");
        jbCadastrarCorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarCordaActionPerformed(evt);
            }
        });

        jbLimparCorda.setText("Limpar");
        jbLimparCorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparCordaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jbCadastrarCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(jbLimparCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimparCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrarCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cadastrarCorda(){
        try {
            InstrumentoCordasVO cVO = new InstrumentoCordasVO();
            cVO.setMarca(jtMarcaCorda.getText());
            cVO.setModelo(jtModeloCorda.getText());
            cVO.setAno(Integer.parseInt(jtAnoCorda.getText()));
            cVO.setValorCustoCordas(Double.parseDouble(jtValorCustoCorda.getText()));
            cVO.setQuantidade(Integer.parseInt(jtQuantidadeCorda.getText()));
            
            InstrumentoCordaServicos cs = servicos.ServicosFactory.getInstrumentoCordasServicos();
            cs.cadastrarInstrumentoCorda(cVO);
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Instrumento cadastrado com sucesso!");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//Fecha cadastrarCorda
    
    private void limparCorda(){
        jtMarcaCorda.setText("");
        jtModeloCorda.setText("");
        jtAnoCorda.setText("");
        jtValorCustoCorda.setText("");
        jtQuantidadeCorda.setText("");
        
        jtMarcaCorda.grabFocus();
    }
    
    private void jbCadastrarCordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarCordaActionPerformed
        // TODO add your handling code here:
        cadastrarCorda();
        limparCorda();
    }//GEN-LAST:event_jbCadastrarCordaActionPerformed

    private void jbLimparCordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparCordaActionPerformed
        // TODO add your handling code here:
        limparCorda();
    }//GEN-LAST:event_jbLimparCordaActionPerformed

    private void jtMarcaCordaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMarcaCordaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtModeloCorda.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtMarcaCordaKeyPressed

    private void jtModeloCordaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtModeloCordaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtAnoCorda.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtModeloCordaKeyPressed

    private void jtAnoCordaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAnoCordaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtValorCustoCorda.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtAnoCordaKeyPressed

    private void jtValorCustoCordaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValorCustoCordaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtQuantidadeCorda.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtValorCustoCordaKeyPressed

    private void jtQuantidadeCordaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtQuantidadeCordaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarCorda();
            limparCorda();
        }//fecha if
    }//GEN-LAST:event_jtQuantidadeCordaKeyPressed

    private void jtMarcaCordaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMarcaCordaFocusLost
        // TODO add your handling code here:
        if(jtMarcaCorda.getText() .isEmpty()){
            jlMarcaCordaErro.setVisible(true);
            jtMarcaCorda.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtMarcaCorda.setBorder(BorderFactory.createLineBorder(Color.black));
            jlMarcaCordaErro.setVisible(false);
        }
    }//GEN-LAST:event_jtMarcaCordaFocusLost

    private void jtModeloCordaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtModeloCordaFocusLost
        // TODO add your handling code here:
        if(jtModeloCorda.getText() .isEmpty()){
            jlModeloCordaErro.setVisible(true);
            jtModeloCorda.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtModeloCorda.setBorder(BorderFactory.createLineBorder(Color.black));
            jlModeloCordaErro.setVisible(false);
        }
    }//GEN-LAST:event_jtModeloCordaFocusLost

    private void jtAnoCordaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAnoCordaFocusLost
        // TODO add your handling code here:
        
        if(jtAnoCorda.getText() .isEmpty()){
            jlAnoCordaErro.setVisible(true);
            jtAnoCorda.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtAnoCorda.setBorder(BorderFactory.createLineBorder(Color.black));
            jlAnoCordaErro.setVisible(false);
        }
    }//GEN-LAST:event_jtAnoCordaFocusLost

    private void jtValorCustoCordaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorCustoCordaFocusLost
        // TODO add your handling code here:
        if(jtValorCustoCorda.getText() .isEmpty()){
            jlValorCustoCordaErro.setVisible(true);
            jtValorCustoCorda.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jlValorCustoCordaErro.setVisible(false);
            jtValorCustoCorda.setBorder(BorderFactory.createLineBorder(Color.black));
        }
    }//GEN-LAST:event_jtValorCustoCordaFocusLost

    private void jtQuantidadeCordaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuantidadeCordaFocusLost
        // TODO add your handling code here:
        if(jtQuantidadeCorda.getText() .isEmpty()){
            jlQuantidadeCordaErro.setVisible(true);
            jtQuantidadeCorda.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jlQuantidadeCordaErro.setVisible(false);
            jtQuantidadeCorda.setBorder(BorderFactory.createLineBorder(Color.black));
        }
    }//GEN-LAST:event_jtQuantidadeCordaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCadastrarCorda;
    private javax.swing.JButton jbLimparCorda;
    private javax.swing.JLabel jlAnoCorda;
    private javax.swing.JLabel jlAnoCordaErro;
    private javax.swing.JLabel jlMarcaCorda;
    private javax.swing.JLabel jlMarcaCordaErro;
    private javax.swing.JLabel jlModeloCorda;
    private javax.swing.JLabel jlModeloCordaErro;
    private javax.swing.JLabel jlQuantidadeCorda;
    private javax.swing.JLabel jlQuantidadeCordaErro;
    private javax.swing.JLabel jlValorCorda;
    private javax.swing.JLabel jlValorCustoCordaErro;
    private javax.swing.JTextField jtAnoCorda;
    private javax.swing.JTextField jtMarcaCorda;
    private javax.swing.JTextField jtModeloCorda;
    private javax.swing.JTextField jtQuantidadeCorda;
    private javax.swing.JTextField jtValorCustoCorda;
    // End of variables declaration//GEN-END:variables
}
