/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.InstrumentoPercussaoVO;
import servicos.InstrumentoPercussaoServicos;

/**
 *
 * @author William Soares
 * @since 07/07/2018
 * @version 1.0
 */
public class GUICadInstrumentosPerc extends javax.swing.JInternalFrame {
    /**
     * Creates new form GUICadInstrumentosPerc
     */
    public GUICadInstrumentosPerc() {
        initComponents();
        jlMarcaPercErro.setVisible(false);
        jlModeloPercErro.setVisible(false);
        jlAnoPercErro.setVisible(false);
        jlValorCustoPercErro.setVisible(false);
        jlQuantidadePercErro.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlMarcaPerc = new javax.swing.JLabel();
        jlModeloPerc = new javax.swing.JLabel();
        jtMarcaPerc = new javax.swing.JTextField();
        jtModeloPerc = new javax.swing.JTextField();
        jlValorPerc = new javax.swing.JLabel();
        jlQuantidadePerc = new javax.swing.JLabel();
        jtValorCustoPerc = new javax.swing.JTextField();
        jtQuantidadePerc = new javax.swing.JTextField();
        jlAnoPerc = new javax.swing.JLabel();
        jtAnoPerc = new javax.swing.JTextField();
        jlMarcaPercErro = new javax.swing.JLabel();
        jlModeloPercErro = new javax.swing.JLabel();
        jlAnoPercErro = new javax.swing.JLabel();
        jlValorCustoPercErro = new javax.swing.JLabel();
        jlQuantidadePercErro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbCadastrarPerc = new javax.swing.JButton();
        jbLimparPerc = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro de Instrumento (Percussao)");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlMarcaPerc.setText("Marca");

        jlModeloPerc.setText("Modelo");

        jtMarcaPerc.setForeground(java.awt.Color.black);
        jtMarcaPerc.setDisabledTextColor(java.awt.Color.black);
        jtMarcaPerc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMarcaPercFocusLost(evt);
            }
        });
        jtMarcaPerc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtMarcaPercKeyPressed(evt);
            }
        });

        jtModeloPerc.setForeground(java.awt.Color.black);
        jtModeloPerc.setDisabledTextColor(java.awt.Color.black);
        jtModeloPerc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtModeloPercFocusLost(evt);
            }
        });
        jtModeloPerc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtModeloPercKeyPressed(evt);
            }
        });

        jlValorPerc.setText("Valor Custo");

        jlQuantidadePerc.setText("Quantidade");

        jtValorCustoPerc.setDisabledTextColor(java.awt.Color.black);
        jtValorCustoPerc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtValorCustoPercFocusLost(evt);
            }
        });
        jtValorCustoPerc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValorCustoPercKeyPressed(evt);
            }
        });

        jtQuantidadePerc.setDisabledTextColor(java.awt.Color.black);
        jtQuantidadePerc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuantidadePercFocusLost(evt);
            }
        });
        jtQuantidadePerc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtQuantidadePercKeyPressed(evt);
            }
        });

        jlAnoPerc.setText("Ano");

        jtAnoPerc.setDisabledTextColor(java.awt.Color.black);
        jtAnoPerc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAnoPercFocusLost(evt);
            }
        });
        jtAnoPerc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAnoPercKeyPressed(evt);
            }
        });

        jlMarcaPercErro.setForeground(java.awt.Color.red);
        jlMarcaPercErro.setText("*Preencha este campo");

        jlModeloPercErro.setForeground(java.awt.Color.red);
        jlModeloPercErro.setText("*Preencha este campo");

        jlAnoPercErro.setForeground(java.awt.Color.red);
        jlAnoPercErro.setText("*Preencha este campo");

        jlValorCustoPercErro.setForeground(java.awt.Color.red);
        jlValorCustoPercErro.setText("*Preencha este campo");

        jlQuantidadePercErro.setForeground(java.awt.Color.red);
        jlQuantidadePercErro.setText("*Preencha este campo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlQuantidadePerc)
                        .addGap(35, 35, 35)
                        .addComponent(jtQuantidadePerc, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlValorPerc)
                        .addGap(36, 36, 36)
                        .addComponent(jtValorCustoPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlMarcaPerc)
                        .addGap(64, 64, 64)
                        .addComponent(jtMarcaPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlModeloPerc)
                        .addGap(58, 58, 58)
                        .addComponent(jtModeloPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlAnoPerc)
                        .addGap(78, 78, 78)
                        .addComponent(jtAnoPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlQuantidadePercErro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jlValorCustoPercErro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlAnoPercErro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlModeloPercErro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlMarcaPercErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMarcaPerc)
                    .addComponent(jtMarcaPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMarcaPercErro))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtModeloPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlModeloPerc)
                    .addComponent(jlModeloPercErro))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAnoPerc)
                    .addComponent(jtAnoPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAnoPercErro))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorPerc)
                    .addComponent(jtValorCustoPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValorCustoPercErro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQuantidadePerc)
                    .addComponent(jtQuantidadePerc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidadePercErro))
                .addGap(68, 68, 68))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrarPerc.setText("Cadastrar");
        jbCadastrarPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarPercActionPerformed(evt);
            }
        });

        jbLimparPerc.setText("Limpar");
        jbLimparPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparPercActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jbCadastrarPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimparPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimparPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cadastrarPercussao(){
        try {
            InstrumentoPercussaoVO pVO = new InstrumentoPercussaoVO();
            pVO.setMarca(jtMarcaPerc.getText());
            pVO.setModelo(jtModeloPerc.getText());
            pVO.setAno(Integer.parseInt(jtAnoPerc.getText()));
            pVO.setValorcusto(Double.parseDouble(jtValorCustoPerc.getText()));
            pVO.setQuantidade(Integer.parseInt(jtQuantidadePerc.getText()));
            
            InstrumentoPercussaoServicos ps = servicos.ServicosFactory.getInstrumentoPercussaoServicos();
            ps.cadastrarInstrumentoPercussao(pVO);
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Instrumento cadastrado com sucesso!");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//Fecha cadastrarCorda
    
    private void limparPercussao(){
        jtMarcaPerc.setText("");
        jtModeloPerc.setText("");
        jtAnoPerc.setText("");
        jtValorCustoPerc.setText("");
        jtQuantidadePerc.setText("");
        
        jtMarcaPerc.grabFocus();
    }
    
    private void jbCadastrarPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarPercActionPerformed
        // TODO add your handling code here:
        cadastrarPercussao();
        limparPercussao();
    }//GEN-LAST:event_jbCadastrarPercActionPerformed

    private void jbLimparPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparPercActionPerformed
        // TODO add your handling code here:
        limparPercussao();
    }//GEN-LAST:event_jbLimparPercActionPerformed

    private void jtMarcaPercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMarcaPercKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtModeloPerc.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtMarcaPercKeyPressed

    private void jtModeloPercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtModeloPercKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtAnoPerc.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtModeloPercKeyPressed

    private void jtAnoPercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAnoPercKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtValorCustoPerc.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtAnoPercKeyPressed

    private void jtValorCustoPercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValorCustoPercKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtQuantidadePerc.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtValorCustoPercKeyPressed

    private void jtMarcaPercFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMarcaPercFocusLost
        // TODO add your handling code here:
        if(jtMarcaPerc.getText() .isEmpty()){
            jlMarcaPercErro.setVisible(true);
            jtMarcaPerc.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtMarcaPerc.setBorder(BorderFactory.createLineBorder(Color.black));
            jlMarcaPercErro.setVisible(false);
        }
    }//GEN-LAST:event_jtMarcaPercFocusLost

    private void jtModeloPercFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtModeloPercFocusLost
        // TODO add your handling code here:
        if(jtModeloPerc.getText() .isEmpty()){
            jlModeloPercErro.setVisible(true);
            jtModeloPerc.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtModeloPerc.setBorder(BorderFactory.createLineBorder(Color.black));
            jlModeloPercErro.setVisible(false);
        }
    }//GEN-LAST:event_jtModeloPercFocusLost

    private void jtAnoPercFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAnoPercFocusLost
        // TODO add your handling code here:
        if(jtAnoPerc.getText() .isEmpty()){
            jlAnoPercErro.setVisible(true);
            jtAnoPerc.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtAnoPerc.setBorder(BorderFactory.createLineBorder(Color.black));
            jlAnoPercErro.setVisible(false);
        }
    }//GEN-LAST:event_jtAnoPercFocusLost

    private void jtValorCustoPercFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtValorCustoPercFocusLost
        // TODO add your handling code here:
        if(jtMarcaPerc.getText() .isEmpty()){
            jlValorCustoPercErro.setVisible(true);
            jtValorCustoPerc.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtValorCustoPerc.setBorder(BorderFactory.createLineBorder(Color.black));
            jlValorCustoPercErro.setVisible(false);
        }
    }//GEN-LAST:event_jtValorCustoPercFocusLost

    private void jtQuantidadePercKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtQuantidadePercKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarPercussao();
            limparPercussao();
        }//fecha if
    }//GEN-LAST:event_jtQuantidadePercKeyPressed

    private void jtQuantidadePercFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuantidadePercFocusLost
        // TODO add your handling code here:
        if(jtQuantidadePerc.getText() .isEmpty()){
            jlQuantidadePercErro.setVisible(true);
            jtQuantidadePerc.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtQuantidadePerc.setBorder(BorderFactory.createLineBorder(Color.black));
            jlQuantidadePercErro.setVisible(false);
        }
    }//GEN-LAST:event_jtQuantidadePercFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbCadastrarPerc;
    private javax.swing.JButton jbLimparPerc;
    private javax.swing.JLabel jlAnoPerc;
    private javax.swing.JLabel jlAnoPercErro;
    private javax.swing.JLabel jlMarcaPerc;
    private javax.swing.JLabel jlMarcaPercErro;
    private javax.swing.JLabel jlModeloPerc;
    private javax.swing.JLabel jlModeloPercErro;
    private javax.swing.JLabel jlQuantidadePerc;
    private javax.swing.JLabel jlQuantidadePercErro;
    private javax.swing.JLabel jlValorCustoPercErro;
    private javax.swing.JLabel jlValorPerc;
    private javax.swing.JTextField jtAnoPerc;
    private javax.swing.JTextField jtMarcaPerc;
    private javax.swing.JTextField jtModeloPerc;
    private javax.swing.JTextField jtQuantidadePerc;
    private javax.swing.JTextField jtValorCustoPerc;
    // End of variables declaration//GEN-END:variables
}
