/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.InstrumentoCordasVO;
import modelo.InstrumentoPercussaoVO;
import servicos.InstrumentoPercussaoServicos;
import servicos.ServicosFactory;

/**
 *
 * @author william
 */
public class GUIManInstrumentosPerc extends javax.swing.JInternalFrame {
    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Marca", "Modelo", "Ano", "Valor", "Quantidade"});

    /**
     * Creates new form GUIManInstrumentosPerc
     */
    public GUIManInstrumentosPerc() {
        initComponents();
        preencherTabelaPerc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableInstumentoPerc = new javax.swing.JTable();
        jtPesq = new javax.swing.JTextField();
        jcomboFiltroPerc = new javax.swing.JComboBox<>();
        jtCodigoPerc = new javax.swing.JTextField();
        jtMarcaPerc = new javax.swing.JTextField();
        jtModeloPerc = new javax.swing.JTextField();
        jtAnoPerc = new javax.swing.JTextField();
        jtValorCustoPerc = new javax.swing.JTextField();
        jtQuantidadePerc = new javax.swing.JTextField();
        jbConfirmarAlteracao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbPreencherPerc = new javax.swing.JButton();
        jbLimparPerc = new javax.swing.JButton();
        jbDeletarPerc = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableInstumentoPerc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Modelo", "Ano", "Valor Custo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableInstumentoPerc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableInstumentoPercMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableInstumentoPerc);
        if (jtableInstumentoPerc.getColumnModel().getColumnCount() > 0) {
            jtableInstumentoPerc.getColumnModel().getColumn(0).setResizable(false);
            jtableInstumentoPerc.getColumnModel().getColumn(1).setResizable(false);
            jtableInstumentoPerc.getColumnModel().getColumn(2).setResizable(false);
            jtableInstumentoPerc.getColumnModel().getColumn(3).setResizable(false);
            jtableInstumentoPerc.getColumnModel().getColumn(4).setResizable(false);
            jtableInstumentoPerc.getColumnModel().getColumn(5).setResizable(false);
        }

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jcomboFiltroPerc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca", "Modelo", "Valor Custo", "Ano", "Quantidade", "Codigo" }));
        jcomboFiltroPerc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboFiltroPercItemStateChanged(evt);
            }
        });

        jtCodigoPerc.setEditable(false);

        jbConfirmarAlteracao.setText("Confirmar Alteracao");
        jbConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcomboFiltroPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtCodigoPerc, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jtAnoPerc))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtMarcaPerc, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jtValorCustoPerc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtQuantidadePerc, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(jtModeloPerc))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jbConfirmarAlteracao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboFiltroPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCodigoPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMarcaPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtModeloPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAnoPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtValorCustoPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtQuantidadePerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jbConfirmarAlteracao)
                .addGap(26, 26, 26))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPreencherPerc.setText("Atualizar Tabela");
        jbPreencherPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherPercActionPerformed(evt);
            }
        });

        jbLimparPerc.setText("Limpar Tabela");
        jbLimparPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparPercActionPerformed(evt);
            }
        });

        jbDeletarPerc.setText("Deletar");
        jbDeletarPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarPercActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jbPreencherPerc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimparPerc)
                .addGap(251, 251, 251)
                .addComponent(jbDeletarPerc)
                .addGap(89, 89, 89))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbPreencherPerc)
                            .addComponent(jbLimparPerc)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jbDeletarPerc)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void preencherTabelaPerc(){
        try {

            InstrumentoPercussaoServicos ps = ServicosFactory.getInstrumentoPercussaoServicos();

            ArrayList<InstrumentoPercussaoVO> perc = new ArrayList<>();

            perc = ps.buscarInstrumentoPercussao();

            for (int i = 0; i < perc.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(perc.get(i).getIdInstrumentoPercussao()),
                    String.valueOf(perc.get(i).getMarca()),
                    String.valueOf(perc.get(i).getModelo()),
                    String.valueOf(perc.get(i).getAno()),
                    String.valueOf(perc.get(i).getValorcusto()),
                    String.valueOf(perc.get(i).getQuantidade())
                });
            }//fecha for

            jtableInstumentoPerc.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    }//Fecha preencher tabela corda
    
    private void limparTabelaPercussao() {      
        dtm.setNumRows(0);
        
    }//fecha limparTabelaCorda
    
    private void deletarPercussao(){
        try {
            int linha = jtableInstumentoPerc.getSelectedRow();
            
            if(linha == -1){
                JOptionPane.showMessageDialog(
                        rootPane, 
                        "Selecione uma linha!");
            }else{
                String id = jtableInstumentoPerc.getValueAt(linha, 0).toString();
                InstrumentoPercussaoServicos PS = ServicosFactory.getInstrumentoPercussaoServicos();
                PS.deletarInstrumentoPercussao(Long.parseLong(id));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage());
        }
    }//fecha deletarCorda
    
    private void filtrarPercussao(){
        try {
            
            if(jtPesq.getText() .isEmpty()){
                limparTabelaPercussao();
                preencherTabelaPerc();
            }else{
                
                String query = "";
                String filtro = jcomboFiltroPerc.getSelectedItem().toString();
                
                if(filtro.equalsIgnoreCase("Marca")){
                    query = "where marca like '%"+jtPesq.getText()+"%'";
                }else if (filtro.equalsIgnoreCase("Modelo")){
                    query = "where modelo like '%"+jtPesq.getText()+"%'";
                }else if (filtro.equalsIgnoreCase("Codigo")){
                    query = "where idinstrumentopercussao = "+jtPesq.getText();
                }else if(filtro.equalsIgnoreCase("Valor")){
                    query = "where valorcusto like '%"+jtPesq.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("Quantidade")){
                    query = "where quantidade like '%"+jtPesq.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("Ano")){
                    query = "where ano like '%"+jtPesq.getText()+"%'";
                }//fecha else if
                
                InstrumentoPercussaoServicos PS = ServicosFactory.getInstrumentoPercussaoServicos();
                ArrayList<InstrumentoPercussaoVO> perc = PS.filtrar(query);
                
                for(int i=0 ; i<perc.size() ; i++){
                    dtm.addRow(new String[]{
                        String.valueOf(perc.get(i).getIdInstrumentoPercussao()),
                        perc.get(i).getMarca(),
                        perc.get(i).getModelo(),
                        String.valueOf(perc.get(i).getAno()),
                        String.valueOf(perc.get(i).getValorcusto()),
                        String.valueOf(perc.get(i).getQuantidade()),
                    });
                }
                
                jtableInstumentoPerc.setModel(dtm);
                
            }//fecha else
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro "+e.getMessage());
        }
    }//fecha filtrarCorda
    
    private void alterarInstrumentoPercussao(){
       int linha = jtableInstumentoPerc.getSelectedRow();
        String codigo = jtableInstumentoPerc.getValueAt(linha, 0).toString();
        String marca = jtableInstumentoPerc.getValueAt(linha, 1).toString();
        String modelo = jtableInstumentoPerc.getValueAt(linha, 2).toString();
        String ano = jtableInstumentoPerc.getValueAt(linha, 3).toString();
        String valorCusto = jtableInstumentoPerc.getValueAt(linha, 4).toString();
        String quantidade = jtableInstumentoPerc.getValueAt(linha, 5).toString();

        jtCodigoPerc.setText(codigo);
        jtMarcaPerc.setText(marca);
        jtModeloPerc.setText(modelo);
        jtAnoPerc.setText(ano);
        jtValorCustoPerc.setText(valorCusto);
        jtQuantidadePerc.setText(quantidade);
        
    }//Fecha alterarInstrumentoCorda
    
    private void confirmarAlteracaoPercussao() {
        try {
            InstrumentoPercussaoVO pVO = new InstrumentoPercussaoVO();
            pVO.setIdInstrumentoPercussao(Long.parseLong(jtCodigoPerc.getText()));
            pVO.setMarca(jtMarcaPerc.getText());
            pVO.setModelo(jtModeloPerc.getText());
            pVO.setAno(Integer.parseInt(jtAnoPerc.getText()));
            pVO.setValorcusto(Double.parseDouble(jtValorCustoPerc.getText()));
            pVO.setQuantidade(Integer.parseInt(jtQuantidadePerc.getText()));

            InstrumentoPercussaoServicos ps = servicos.ServicosFactory.getInstrumentoPercussaoServicos();
            ps.alterarInstrumentoPercussao(pVO);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Instrumento alterado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//Fecha confirmarAlteracaoCorda
    
    private void limparCamposPercussao() {
        jtCodigoPerc.setText("");
        jtMarcaPerc.setText("");
        jtModeloPerc.setText("");
        jtAnoPerc.setText("");
        jtValorCustoPerc.setText("");
        jtQuantidadePerc.setText("");
    }  
    
    private void jbPreencherPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherPercActionPerformed
        // TODO add your handling code here:
        limparTabelaPercussao();
        preencherTabelaPerc();
    }//GEN-LAST:event_jbPreencherPercActionPerformed

    private void jbLimparPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparPercActionPerformed
        // TODO add your handling code here:
        limparTabelaPercussao();
        preencherTabelaPerc();
    }//GEN-LAST:event_jbLimparPercActionPerformed

    private void jbDeletarPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarPercActionPerformed
        // TODO add your handling code here:
        limparTabelaPercussao();
    }//GEN-LAST:event_jbDeletarPercActionPerformed

    private void jbConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoActionPerformed
        // TODO add your handling code here:
        confirmarAlteracaoPercussao();
        limparTabelaPercussao();
        preencherTabelaPerc();
        limparCamposPercussao();
    }//GEN-LAST:event_jbConfirmarAlteracaoActionPerformed

    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        // TODO add your handling code here:
        limparTabelaPercussao();
        preencherTabelaPerc();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jcomboFiltroPercItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboFiltroPercItemStateChanged
        // TODO add your handling code here:
        limparTabelaPercussao();
        filtrarPercussao();
    }//GEN-LAST:event_jcomboFiltroPercItemStateChanged

    private void jtableInstumentoPercMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableInstumentoPercMouseClicked
        // TODO add your handling code here:
        alterarInstrumentoPercussao();
    }//GEN-LAST:event_jtableInstumentoPercMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbConfirmarAlteracao;
    private javax.swing.JButton jbDeletarPerc;
    private javax.swing.JButton jbLimparPerc;
    private javax.swing.JButton jbPreencherPerc;
    private javax.swing.JComboBox<String> jcomboFiltroPerc;
    private javax.swing.JTextField jtAnoPerc;
    private javax.swing.JTextField jtCodigoPerc;
    private javax.swing.JTextField jtMarcaPerc;
    private javax.swing.JTextField jtModeloPerc;
    private javax.swing.JTextField jtPesq;
    private javax.swing.JTextField jtQuantidadePerc;
    private javax.swing.JTextField jtValorCustoPerc;
    private javax.swing.JTable jtableInstumentoPerc;
    // End of variables declaration//GEN-END:variables
}
