/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.InstrumentoCordasVO;
import servicos.InstrumentoCordaServicos;
import servicos.ServicosFactory;

/**
 *
 * @author William Soares
 * @since 07/07/2018
 * @version 1.0
 */
public class GUIManInstrumentosCordas extends javax.swing.JInternalFrame {
    
    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código", "Marca", "Modelo", "Ano", "Valor", "Quantidade"});
    /**
     * Creates new form GUIManInstrumentosCordas
     */
    public GUIManInstrumentosCordas() {
        initComponents();
        preencherTabelaCorda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jtPesq = new javax.swing.JTextField();
        jcomboFiltroCorda = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableInstrumentoCorda = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jtCodigoCorda = new javax.swing.JTextField();
        jtMarcaCorda = new javax.swing.JTextField();
        jtModeloCorda = new javax.swing.JTextField();
        jtAnoCorda = new javax.swing.JTextField();
        jtValorCustoCorda = new javax.swing.JTextField();
        jtQuantidadeCorda = new javax.swing.JTextField();
        jbConfirmarAlteracao = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jbPreencher = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jcomboFiltroCorda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca", "Codigo", "Modelo", "Valor", "Quantidade", "Ano" }));
        jcomboFiltroCorda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcomboFiltroCordaItemStateChanged(evt);
            }
        });

        jtableInstrumentoCorda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Modelo", "Ano", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableInstrumentoCorda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableInstrumentoCordaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableInstrumentoCorda);

        jLayeredPane1.setLayer(jtPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcomboFiltroCorda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcomboFiltroCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboFiltroCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtCodigoCorda.setEditable(false);

        jbConfirmarAlteracao.setText("Confirmar Alteracao");
        jbConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jtCodigoCorda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtMarcaCorda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtModeloCorda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtAnoCorda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtValorCustoCorda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jtQuantidadeCorda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbConfirmarAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCodigoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtAnoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtMarcaCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtValorCustoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtModeloCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtQuantidadeCorda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jbConfirmarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCodigoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtMarcaCorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtModeloCorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAnoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtValorCustoCorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtQuantidadeCorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jbConfirmarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPreencher.setText("Atualizar Tabela");
        jbPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar Tabela");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jbPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jbPreencher)
                .addGap(202, 202, 202)
                .addComponent(jbLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbDeletar)
                .addGap(130, 130, 130))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void preencherTabelaCorda(){
        try {

            InstrumentoCordaServicos cs = ServicosFactory.getInstrumentoCordasServicos();

            ArrayList<InstrumentoCordasVO> cordas = new ArrayList<>();

            cordas = cs.buscarInstrumentoCordas();

            for (int i = 0; i < cordas.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(cordas.get(i).getIdInstrumentoCorda()),
                    String.valueOf(cordas.get(i).getMarca()),
                    String.valueOf(cordas.get(i).getModelo()),
                    String.valueOf(cordas.get(i).getAno()),
                    String.valueOf(cordas.get(i).getValorCustoCordas()),
                    String.valueOf(cordas.get(i).getQuantidade())
                });
            }//fecha for

            jtableInstrumentoCorda.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    }//Fecha preencher tabela corda
    
    private void limparTabelaCorda() {      
        dtm.setNumRows(0);
        
    }//fecha limparTabelaCorda
    
    private void deletarCorda(){
        try {
            int linha = jtableInstrumentoCorda.getSelectedRow();
            
            if(linha == -1){
                JOptionPane.showMessageDialog(
                        rootPane, 
                        "Selecione uma linha!");
            }else{
                String id = jtableInstrumentoCorda.getValueAt(linha, 0).toString();
                InstrumentoCordaServicos CS = ServicosFactory.getInstrumentoCordasServicos();
                CS.deletarInstrumentoCorda(Long.parseLong(id));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage());
        }
    }//fecha deletarCorda
    
    private void filtrarCorda(){
        try {
            
            if(jtPesq.getText() .isEmpty()){
                limparTabelaCorda();
                preencherTabelaCorda();
            }else{
                
                String query = "";
                String filtro = jcomboFiltroCorda.getSelectedItem().toString();
                
                if(filtro.equalsIgnoreCase("Marca")){
                    query = "where marca like '%"+jtPesq.getText()+"%'";
                }else if (filtro.equalsIgnoreCase("Modelo")){
                    query = "where modelo like '%"+jtPesq.getText()+"%'";
                }else if (filtro.equalsIgnoreCase("Codigo")){
                    query = "where idinstrumentocorda = "+jtPesq.getText();
                }else if(filtro.equalsIgnoreCase("Valor")){
                    query = "where valorcusto like '%"+jtPesq.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("Quantidade")){
                    query = "where quantidade like '%"+jtPesq.getText()+"%'";
                }else if(filtro.equalsIgnoreCase("Ano")){
                    query = "where ano like '%"+jtPesq.getText()+"%'";
                }//fecha else if
                
                InstrumentoCordaServicos CS = ServicosFactory.getInstrumentoCordasServicos();
                ArrayList<InstrumentoCordasVO> cordas = CS.filtrar(query);
                
                for(int i=0 ; i<cordas.size() ; i++){
                    dtm.addRow(new String[]{
                        String.valueOf(cordas.get(i).getIdInstrumentoCorda()),
                        cordas.get(i).getMarca(),
                        cordas.get(i).getModelo(),
                        String.valueOf(cordas.get(i).getAno()),
                        String.valueOf(cordas.get(i).getValorCustoCordas()),
                        String.valueOf(cordas.get(i).getQuantidade()),
                    });
                }
                
                jtableInstrumentoCorda.setModel(dtm);
                
            }//fecha else
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro "+e.getMessage());
        }
    }//fecha filtrarCorda
    
    private void alterarInstrumentoCorda(){
       int linha = jtableInstrumentoCorda.getSelectedRow();
        String codigo = jtableInstrumentoCorda.getValueAt(linha, 0).toString();
        String marca = jtableInstrumentoCorda.getValueAt(linha, 1).toString();
        String modelo = jtableInstrumentoCorda.getValueAt(linha, 2).toString();
        String ano = jtableInstrumentoCorda.getValueAt(linha, 3).toString();
        String valorCusto = jtableInstrumentoCorda.getValueAt(linha, 4).toString();
        String quantidade = jtableInstrumentoCorda.getValueAt(linha, 5).toString();

        jtCodigoCorda.setText(codigo);
        jtMarcaCorda.setText(marca);
        jtModeloCorda.setText(modelo);
        jtAnoCorda.setText(ano);
        jtValorCustoCorda.setText(valorCusto);
        jtQuantidadeCorda.setText(quantidade);
        
    }//Fecha alterarInstrumentoCorda
    
    private void confirmarAlteracaoCorda() {
        try {
            InstrumentoCordasVO cVO = new InstrumentoCordasVO();
            cVO.setIdInstrumentoCorda(Long.parseLong(jtCodigoCorda.getText()));
            cVO.setMarca(jtMarcaCorda.getText());
            cVO.setModelo(jtModeloCorda.getText());
            cVO.setAno(Integer.parseInt(jtAnoCorda.getText()));
            cVO.setValorCustoCordas(Double.parseDouble(jtValorCustoCorda.getText()));
            cVO.setQuantidade(Integer.parseInt(jtQuantidadeCorda.getText()));

            InstrumentoCordaServicos cs = servicos.ServicosFactory.getInstrumentoCordasServicos();
            cs.alterarInstrumentoCorda(cVO);

            JOptionPane.showMessageDialog(
                    rootPane,
                    "Instrumento alterado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//Fecha confirmarAlteracaoCorda
    
    private void limparCamposCorda() {
        jtCodigoCorda.setText("");
        jtMarcaCorda.setText("");
        jtModeloCorda.setText("");
        jtAnoCorda.setText("");
        jtValorCustoCorda.setText("");
        jtQuantidadeCorda.setText("");
    }  
    
    private void jbConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoActionPerformed
        // TODO add your handling code here:
        confirmarAlteracaoCorda();
        limparTabelaCorda();
        preencherTabelaCorda();
        limparCamposCorda();
    }//GEN-LAST:event_jbConfirmarAlteracaoActionPerformed

    private void jbPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherActionPerformed
        // TODO add your handling code here:
        limparTabelaCorda();
        preencherTabelaCorda();
    }//GEN-LAST:event_jbPreencherActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limparTabelaCorda();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        // TODO add your handling code here:
        deletarCorda();
        limparTabelaCorda();
        preencherTabelaCorda();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        // TODO add your handling code here:
        limparTabelaCorda();
        filtrarCorda();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jcomboFiltroCordaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcomboFiltroCordaItemStateChanged
        // TODO add your handling code here:
        limparTabelaCorda();
        filtrarCorda();
    }//GEN-LAST:event_jcomboFiltroCordaItemStateChanged

    private void jtableInstrumentoCordaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableInstrumentoCordaMouseClicked
        // TODO add your handling code here:
        alterarInstrumentoCorda();
    }//GEN-LAST:event_jtableInstrumentoCordaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbConfirmarAlteracao;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPreencher;
    private javax.swing.JComboBox<String> jcomboFiltroCorda;
    private javax.swing.JTextField jtAnoCorda;
    private javax.swing.JTextField jtCodigoCorda;
    private javax.swing.JTextField jtMarcaCorda;
    private javax.swing.JTextField jtModeloCorda;
    private javax.swing.JTextField jtPesq;
    private javax.swing.JTextField jtQuantidadeCorda;
    private javax.swing.JTextField jtValorCustoCorda;
    private javax.swing.JTable jtableInstrumentoCorda;
    // End of variables declaration//GEN-END:variables
}
