/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.UIManager;

/**
 *
 * @author William Soares
 * @since 05/07/2018
 * @version 1.0
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        jmiCadCordas = new javax.swing.JMenuItem();
        jmiCadPercussao = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManCordas = new javax.swing.JMenuItem();
        jmiManPercussao = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAreaTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/466799_gibson-les-paul-wallpapers_2200x1467_h.jpg"))); // NOI18N
        jAreaTrabalho.setToolTipText("");

        jMenuBar1.setBackground(new java.awt.Color(235, 220, 221));

        jmCadastrar.setText("Cadastro");

        jmiCadCordas.setText("Cordas");
        jmiCadCordas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadCordasActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCadCordas);

        jmiCadPercussao.setText("Percussao");
        jmiCadPercussao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadPercussaoActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCadPercussao);

        jMenuBar1.add(jmCadastrar);

        jmManutencao.setText("Manutenção");

        jmiManCordas.setText("Cordas");
        jmiManCordas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManCordasActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManCordas);

        jmiManPercussao.setText("Percussao");
        jmiManPercussao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManPercussaoActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManPercussao);

        jMenuBar1.add(jmManutencao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 3828, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void abrirCadInstrumentoCorda(){
        GUICadInstrumentosCordas gcic = new GUICadInstrumentosCordas();
        jAreaTrabalho.add(gcic);
        gcic.setVisible(true);
    }//fecha método
    
    private void abrirManInstrumentoCorda(){
        GUIManInstrumentosCordas gmic = new GUIManInstrumentosCordas();
        jAreaTrabalho.add(gmic);
        gmic.setVisible(true);
    }//fecha método
    
    private void abrirCadInstrumentoPercussao(){
        GUICadInstrumentosPerc gcip = new GUICadInstrumentosPerc();
        jAreaTrabalho.add(gcip);
        gcip.setVisible(true);
    }//fecha método
    
    private void abrirManInstrumentoPercussao(){
        GUIManInstrumentosPerc gmip = new GUIManInstrumentosPerc();
        jAreaTrabalho.add(gmip);
        gmip.setVisible(true);
    }//fecha método
    
    private void jmiCadCordasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadCordasActionPerformed
        // TODO add your handling code here:
        abrirCadInstrumentoCorda();
    }//GEN-LAST:event_jmiCadCordasActionPerformed

    private void jmiManCordasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManCordasActionPerformed
        // TODO add your handling code here:
        abrirManInstrumentoCorda();
    }//GEN-LAST:event_jmiManCordasActionPerformed

    private void jmiManPercussaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManPercussaoActionPerformed
        // TODO add your handling code here:
        abrirManInstrumentoPercussao();
    }//GEN-LAST:event_jmiManPercussaoActionPerformed

    private void jmiCadPercussaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadPercussaoActionPerformed
        // TODO add your handling code here:
        abrirCadInstrumentoPercussao();
    }//GEN-LAST:event_jmiCadPercussaoActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        // TODO add your handling code here:
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        } catch (Exception e) {
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAreaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCadCordas;
    private javax.swing.JMenuItem jmiCadPercussao;
    private javax.swing.JMenuItem jmiManCordas;
    private javax.swing.JMenuItem jmiManPercussao;
    // End of variables declaration//GEN-END:variables
}
